In [1]:
import numpy as np
import datetime

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([
    [1,2,3],
    [4,5,6]
])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array(['1', '2', '3'])

array(['1', '2', '3'], dtype='<U1')

In [5]:
a = np.array([1,2,3])

In [6]:
a[1]

2

In [7]:
for item in a:
    print(item)

1
2
3


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [37]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

# 천만개의 데이터 리스트를 셋팅하고 더하는 속도 비교
#### 결론
- numpy array는 list 초기화보다 조금 더 오래 걸리지만 연산 속도는 비교가 안 된다.
- 많은 데이터를 자주 할당만 한다면 list를, 할당은 횟수는 적고 여러 번의 연산이 필요하면 당연 numpy

  (할당만 하고 사용하지 않는 일은 거의 없겠지)

In [35]:
start_time = datetime.datetime.now()
a = np.array(range(1,10000000))
b = np.array(range(1,10000000))
(datetime.datetime.now() - start_time).total_seconds()

2.071369

In [36]:
start_time = datetime.datetime.now()
a + b
(datetime.datetime.now() - start_time).total_seconds()

0.016999

In [32]:
start_time = datetime.datetime.now()
a = list(range(1, 10000000))
b = list(range(1, 10000000))
(datetime.datetime.now() - start_time).total_seconds()

1.960557

In [33]:
start_time = datetime.datetime.now()
result = []
for item1, item2 in zip(a, b):
    result.append(item1 + item2)
(datetime.datetime.now() - start_time).total_seconds()

11.791171

In [34]:
result = []
a = []
b = []

In [38]:
start_time = datetime.datetime.now()
a = np.arange(1,10000000)
b = np.arange(1,10000000)
(datetime.datetime.now() - start_time).total_seconds()

0.015614